name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check code formatting
        run: npm run format:check

      - name: Build action
        run: npm run build

      - name: Verify dist exists
        run: |
          if [ ! -f dist/index.js ]; then
            echo "❌ dist/index.js was not created"
            exit 1
          fi
          echo "✅ dist/index.js created successfully"

      - name: Check for uncommitted changes
        run: |
          if [ -n "$(git status --porcelain dist/)" ]; then
            echo "❌ Built files have uncommitted changes. Please run 'npm run build' and commit the changes."
            git diff dist/
            exit 1
          fi
          echo "✅ Built files are up to date"

  self-test:
    name: Test and Check Coverage
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Check coverage
        uses: ./
        with:
          coverage-file: coverage/lcov.info
          min-coverage: 100
          min-coverage-new-code: ${{ github.event_name == 'pull_request' && '80' || '' }}
          base-branch: ${{ github.base_ref || 'main' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
